repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: format-import
        name: format-import
        entry: python scripts/format-imports.py
        language: system
        types: [ python ]
      - id: format
        name: format
        entry: python scripts/format.py
        language: system
        types: [ python ]
      - id: lint
        name: lint
        entry: python scripts/lint.py
        language: system
        types: [ python ]
      - id: test
        name: test
        entry: python scripts/pytest-run.py
        language: system
        types: [ python ]
      - id: test-cov
        name: test-cov
        entry: python scripts/test-cov.py
        language: system
        types: [ python ]
